{
  enableInfo: 0,
  enableRightFunc: 1,
  enableMine: 1,
  enableFooter: 1,
  enablePos: 0,
  funcArea: {
    groupArr: [
      {
        enableGroupName: 0,
        menuArr: [
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: 'iconfont-tongji',
              imageUrl: '',
            },
            menuName: '菜单1',
            permission: [
              {
                check: '2',
                permissionItemId: 10,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mqygfd',
            menuCode: '',
            menuType: 2,
            backName: '菜单-rIfk1h',
            id: 480,
            configCompName: 'DeployMenuConfig',
            gradientObj: {
              color1: 'rgba(255, 159, 102, 1)',
              color2: 'rgba(253, 90, 38, 1)',
            },
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: 'iconfont-tongji',
              imageUrl: '',
            },
            menuName: '菜单2',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单11',
            id: 1,
            configCompName: 'DeployMenuConfig',
            gradientObj: {
              color1: 'rgba(255, 192, 0, 1)',
              color2: 'rgba(255, 140, 0, 1)',
            },
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: 'iconfont-tongji',
              imageUrl: '',
            },
            menuName: '菜单21',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 2,
            configCompName: 'DeployMenuConfig',
            gradientObj: {
              color1: 'rgba(93, 237, 183, 1)',
              color2: 'rgba(32, 192, 114, 1)',
            },
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: 'iconfont-tongji',
              imageUrl: '',
            },
            menuName: '菜单23',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 3,
            configCompName: 'DeployMenuConfig',
            gradientObj: {
              color1: 'rgba(127, 154, 255, 1)',
              color2: 'rgba(74, 110, 247, 1)',
            },
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: 'iconfont-tongji',
              imageUrl: '',
            },
            menuName: '菜单2',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 481,
            configCompName: 'DeployMenuConfig',
            gradientObj: {
              color1: 'rgba(255, 125, 125, 1)',
              color2: 'rgba(235, 82, 82, 1)',
            },
          },
          {
            childPageConfig: {
              enableInfo: 0,
              enableRightFunc: 1,
              funcArea: {
                groupArr: [
                  {
                    enableGroupName: 1,
                    menuArr: [
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FAB71C',
                          icon: 'iconfont_gongdan',
                          imageUrl: '',
                        },
                        menuName: '菜单-7BcQy6',
                        type: 1,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'configMenu',
                        clientType: 2,
                        compId: 'CPiUHK',
                        menuCode: '',
                        menuType: 2,
                        id: 495,
                        configCompName: 'DeployMenuConfig',
                      },
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FC8256',
                          icon: 'iconfont_tongji',
                          imageUrl: '',
                        },
                        menuName: '菜单-W6DTXH',
                        type: 2,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'sysKnowledge',
                        clientType: 2,
                        compId: '4nwNNZ',
                        menuCode: '',
                        menuType: 2,
                        id: 496,
                        configCompName: 'DeployMenuConfig',
                      },
                    ],
                    compName: 'FuncGroup',
                    compId: 'dUTwc9',
                    rowNum: 4,
                    name: '分组(dUTwc9)',
                    configCompName: 'FuncGroupConfig',
                  },
                ],
                compId: 'ozpJc1',
                configCompName: 'FuncAreaConfig',
              },
              menuName: '菜单3',
              type: 3,
              rotateImg: {
                imgArr: [],
                compId: 'nEGyfK',
                configCompName: 'RotateImgConfig',
              },
              rightFunc: [
                {
                  icon: {
                    color: '#5A80ED',
                    icon: 'icon_gongdan',
                    imageUrl: '',
                  },
                  menuName: '23t',
                  routeName: 'sysNotification',
                  compId: 'WK62wD',
                  enableMenu: 1,
                  backName: '23',
                  id: 490,
                  configCompName: 'FixMenuConfig',
                },
              ],
              enableRotation: 1,
              id: 489,
            },
            groupCompId: 'r602xd',
            menuLevel: 1,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/%E6%96%87%E4%BB%B6%E5%A4%B9.svg',
            },
            menuName: '菜单3',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
            ],
            type: 3,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mr8EaL',
            menuCode: '',
            menuType: 2,
            backName: '菜单-JyevuD',
            id: 489,
            configCompName: 'DeployMenuConfig',
            gradientObj: {
              color1: 'rgba(255, 159, 102, 1)',
              color2: 'rgba(253, 90, 38, 1)',
            },
          },
        ],
        permission: '1',
        compName: 'FuncGroup',
        routeName: 'sysKnowledge',
        compId: 'r602xd',
        rowNum: 5,
        name: '分组1',
        backName: '分组(r602xd)',
        configCompName: 'FuncGroupConfig',
        showStyle: 1,
      },
      // 1 图标 2个
      {
        enableGroupName: 1,
        menuArr: [
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/%E5%85%B6%E4%BB%96%E6%96%87%E4%BB%B6.svg',
            },
            menuName: '菜单1',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mqygfd',
            menuCode: '',
            menuType: 2,
            backName: '菜单-rIfk1h',
            id: 480,
            configCompName: 'DeployMenuConfig',
            bgColor: '#F6F6F8',
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl: 'http://v9.mingcloud.top:9000/v10/icon/DOC.svg',
            },
            menuName: '菜单2',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 481,
            configCompName: 'DeployMenuConfig',
          },
          {
            childPageConfig: {
              enableInfo: 0,
              enableRightFunc: 1,
              funcArea: {
                groupArr: [
                  {
                    enableGroupName: 1,
                    menuArr: [
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FAB71C',
                          icon: 'iconfont_gongdan',
                          imageUrl: '',
                        },
                        menuName: '菜单-7BcQy6',
                        type: 1,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'configMenu',
                        clientType: 2,
                        compId: 'CPiUHK',
                        menuCode: '',
                        menuType: 2,
                        id: 495,
                        configCompName: 'DeployMenuConfig',
                      },
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FC8256',
                          icon: 'iconfont_tongji',
                          imageUrl: '',
                        },
                        menuName: '菜单-W6DTXH',
                        type: 2,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'sysKnowledge',
                        clientType: 2,
                        compId: '4nwNNZ',
                        menuCode: '',
                        menuType: 2,
                        id: 496,
                        configCompName: 'DeployMenuConfig',
                      },
                    ],
                    compName: 'FuncGroup',
                    compId: 'dUTwc9',
                    rowNum: 4,
                    name: '分组(dUTwc9)',
                    configCompName: 'FuncGroupConfig',
                  },
                ],
                compId: 'ozpJc1',
                configCompName: 'FuncAreaConfig',
              },
              menuName: '菜单3',
              type: 3,
              rotateImg: {
                imgArr: [],
                compId: 'nEGyfK',
                configCompName: 'RotateImgConfig',
              },
              rightFunc: [
                {
                  icon: {
                    color: '#5A80ED',
                    icon: 'icon_gongdan',
                    imageUrl: '',
                  },
                  menuName: '23t',
                  routeName: 'sysNotification',
                  compId: 'WK62wD',
                  enableMenu: 1,
                  backName: '23',
                  id: 490,
                  configCompName: 'FixMenuConfig',
                },
              ],
              enableRotation: 1,
              id: 489,
            },
            groupCompId: 'r602xd',
            menuLevel: 1,
            icon: {
              color: '#5A80ED',
              icon: 'iconfont-guzhang',
              imageUrl: '',
            },
            menuName: '菜单3',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
            ],
            type: 3,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mr8EaL',
            menuCode: '',
            menuType: 2,
            backName: '菜单-JyevuD',
            id: 489,
            configCompName: 'DeployMenuConfig',
            bgColor: '#ECF7FD',
          },
        ],
        permission: '1',
        compName: 'FuncGroup',
        routeName: 'sysKnowledge',
        compId: 'r602xd',
        rowNum: 2,
        name: '分组1',
        backName: '分组(r602xd)',
        configCompName: 'FuncGroupConfig',
        showStyle: 1,
      },
      // 2-图片 2个
      {
        enableGroupName: 1,
        menuArr: [
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            menuName: '菜单1',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mqygfd',
            menuCode: '',
            menuType: 2,
            backName: '菜单-rIfk1h',
            id: 480,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gtd.alicdn.com/sns_logo/i1/TB124_3NXXXXXasXVXXSutbFXXX.jpg_240x240xz.jpg',
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            menuName: '菜单2',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 481,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gtd.alicdn.com/sns_logo/i1/TB124_3NXXXXXasXVXXSutbFXXX.jpg_240x240xz.jpg',
          },
          {
            childPageConfig: {
              enableInfo: 0,
              enableRightFunc: 1,
              funcArea: {
                groupArr: [
                  {
                    enableGroupName: 1,
                    menuArr: [
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FAB71C',
                          icon: 'iconfont_gongdan',
                          imageUrl: '',
                        },
                        menuName: '菜单-7BcQy6',
                        type: 1,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'configMenu',
                        clientType: 2,
                        compId: 'CPiUHK',
                        menuCode: '',
                        menuType: 2,
                        id: 495,
                        configCompName: 'DeployMenuConfig',
                      },
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FC8256',
                          icon: 'iconfont_tongji',
                          imageUrl: '',
                        },
                        menuName: '菜单-W6DTXH',
                        type: 2,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'sysKnowledge',
                        clientType: 2,
                        compId: '4nwNNZ',
                        menuCode: '',
                        menuType: 2,
                        id: 496,
                        configCompName: 'DeployMenuConfig',
                      },
                    ],
                    compName: 'FuncGroup',
                    compId: 'dUTwc9',
                    rowNum: 4,
                    name: '分组(dUTwc9)',
                    configCompName: 'FuncGroupConfig',
                  },
                ],
                compId: 'ozpJc1',
                configCompName: 'FuncAreaConfig',
              },
              menuName: '菜单3',
              type: 3,
              rotateImg: {
                imgArr: [],
                compId: 'nEGyfK',
                configCompName: 'RotateImgConfig',
              },
              rightFunc: [
                {
                  icon: {
                    color: '#5A80ED',
                    icon: 'icon_gongdan',
                    imageUrl: '',
                  },
                  menuName: '23t',
                  routeName: 'sysNotification',
                  compId: 'WK62wD',
                  enableMenu: 1,
                  backName: '23',
                  id: 490,
                  configCompName: 'FixMenuConfig',
                },
              ],
              enableRotation: 1,
              id: 489,
            },
            groupCompId: 'r602xd',
            menuLevel: 1,
            menuName: '菜单3',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
            ],
            type: 3,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mr8EaL',
            menuCode: '',
            menuType: 2,
            backName: '菜单-JyevuD',
            id: 489,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201402%2F22%2F20140222171505_rsCXj.thumb.700_0.gif&refer=http%3A%2F%2Fb-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1634991264&t=00ea34550c052ddf868e2ab427ab6ab3',
          },
        ],
        permission: '1',
        compName: 'FuncGroup',
        routeName: 'sysKnowledge',
        compId: 'r602xd',
        rowNum: 2,
        name: '分组1',
        backName: '分组(r602xd)',
        configCompName: 'FuncGroupConfig',
        showStyle: 2,
      },
      // 1 图标 3个
      {
        enableGroupName: 1,
        menuArr: [
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/2%EF%BC%881%EF%BC%89.svg',
            },
            menuName: '菜单1',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mqygfd',
            menuCode: '',
            menuType: 2,
            backName: '菜单-rIfk1h',
            id: 480,
            configCompName: 'DeployMenuConfig',
            bgColor: '#FFF2F1',
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/2%EF%BC%882%EF%BC%89.svg',
            },
            menuName: '菜单2',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 481,
            configCompName: 'DeployMenuConfig',
            bgColor: '#FFF7EA',
          },
          {
            childPageConfig: {
              enableInfo: 0,
              enableRightFunc: 1,
              funcArea: {
                groupArr: [
                  {
                    enableGroupName: 1,
                    menuArr: [
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FAB71C',
                          icon: 'iconfont_gongdan',
                          imageUrl: '',
                        },
                        menuName: '菜单-7BcQy6',
                        type: 1,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'configMenu',
                        clientType: 2,
                        compId: 'CPiUHK',
                        menuCode: '',
                        menuType: 2,
                        id: 495,
                        configCompName: 'DeployMenuConfig',
                      },
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FC8256',
                          icon: 'iconfont_tongji',
                          imageUrl: '',
                        },
                        menuName: '菜单-W6DTXH',
                        type: 2,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'sysKnowledge',
                        clientType: 2,
                        compId: '4nwNNZ',
                        menuCode: '',
                        menuType: 2,
                        id: 496,
                        configCompName: 'DeployMenuConfig',
                      },
                    ],
                    compName: 'FuncGroup',
                    compId: 'dUTwc9',
                    rowNum: 4,
                    name: '分组(dUTwc9)',
                    configCompName: 'FuncGroupConfig',
                  },
                ],
                compId: 'ozpJc1',
                configCompName: 'FuncAreaConfig',
              },
              menuName: '菜单3',
              type: 3,
              rotateImg: {
                imgArr: [],
                compId: 'nEGyfK',
                configCompName: 'RotateImgConfig',
              },
              rightFunc: [
                {
                  icon: {
                    color: '#5A80ED',
                    icon: 'icon_gongdan',
                    imageUrl: '',
                  },
                  menuName: '23t',
                  routeName: 'sysNotification',
                  compId: 'WK62wD',
                  enableMenu: 1,
                  backName: '23',
                  id: 490,
                  configCompName: 'FixMenuConfig',
                },
              ],
              enableRotation: 1,
              id: 489,
            },
            groupCompId: 'r602xd',
            menuLevel: 1,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/2%EF%BC%884%EF%BC%89.svg',
            },
            menuName: '菜单3',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
            ],
            type: 3,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mr8EaL',
            menuCode: '',
            menuType: 2,
            backName: '菜单-JyevuD',
            id: 489,
            configCompName: 'DeployMenuConfig',
            bgColor: '#ECF7FD',
          },
        ],
        permission: '1',
        compName: 'FuncGroup',
        routeName: 'sysKnowledge',
        compId: 'r602xd',
        rowNum: 3,
        name: '一行3个 图标',
        backName: '分组(r602xd)',
        configCompName: 'FuncGroupConfig',
        showStyle: 1,
      },
      // 2-图片 3个
      {
        enableGroupName: 1,
        menuArr: [
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            menuName: '菜单1',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mqygfd',
            menuCode: '',
            menuType: 2,
            backName: '菜单-rIfk1h',
            id: 480,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gtd.alicdn.com/sns_logo/i1/TB124_3NXXXXXasXVXXSutbFXXX.jpg_240x240xz.jpg',
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            menuName: '菜单2',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 481,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gtd.alicdn.com/sns_logo/i1/TB124_3NXXXXXasXVXXSutbFXXX.jpg_240x240xz.jpg',
          },
          {
            childPageConfig: {
              enableInfo: 0,
              enableRightFunc: 1,
              funcArea: {
                groupArr: [
                  {
                    enableGroupName: 1,
                    menuArr: [
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FAB71C',
                          icon: 'iconfont_gongdan',
                          imageUrl: '',
                        },
                        menuName: '菜单-7BcQy6',
                        type: 1,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'configMenu',
                        clientType: 2,
                        compId: 'CPiUHK',
                        menuCode: '',
                        menuType: 2,
                        id: 495,
                        configCompName: 'DeployMenuConfig',
                      },
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FC8256',
                          icon: 'iconfont_tongji',
                          imageUrl: '',
                        },
                        menuName: '菜单-W6DTXH',
                        type: 2,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'sysKnowledge',
                        clientType: 2,
                        compId: '4nwNNZ',
                        menuCode: '',
                        menuType: 2,
                        id: 496,
                        configCompName: 'DeployMenuConfig',
                      },
                    ],
                    compName: 'FuncGroup',
                    compId: 'dUTwc9',
                    rowNum: 4,
                    name: '分组(dUTwc9)',
                    configCompName: 'FuncGroupConfig',
                  },
                ],
                compId: 'ozpJc1',
                configCompName: 'FuncAreaConfig',
              },
              menuName: '菜单3',
              type: 3,
              rotateImg: {
                imgArr: [],
                compId: 'nEGyfK',
                configCompName: 'RotateImgConfig',
              },
              rightFunc: [
                {
                  icon: {
                    color: '#5A80ED',
                    icon: 'icon_gongdan',
                    imageUrl: '',
                  },
                  menuName: '23t',
                  routeName: 'sysNotification',
                  compId: 'WK62wD',
                  enableMenu: 1,
                  backName: '23',
                  id: 490,
                  configCompName: 'FixMenuConfig',
                },
              ],
              enableRotation: 1,
              id: 489,
            },
            groupCompId: 'r602xd',
            menuLevel: 1,
            menuName: '菜单3',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
            ],
            type: 3,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mr8EaL',
            menuCode: '',
            menuType: 2,
            backName: '菜单-JyevuD',
            id: 489,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201402%2F22%2F20140222171505_rsCXj.thumb.700_0.gif&refer=http%3A%2F%2Fb-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1634991264&t=00ea34550c052ddf868e2ab427ab6ab3',
          },
        ],
        permission: '1',
        compName: 'FuncGroup',
        routeName: 'sysKnowledge',
        compId: 'r602xd',
        rowNum: 3,
        name: '一行3个 图片',
        backName: '分组(r602xd)',
        configCompName: 'FuncGroupConfig',
        showStyle: 2,
      },
      // 1 图标 4个
      {
        enableGroupName: 1,
        menuArr: [
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/1%EF%BC%884%EF%BC%89.svg',
            },
            menuName: '菜单1',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mqygfd',
            menuCode: '',
            menuType: 2,
            backName: '菜单-rIfk1h',
            id: 41,
            configCompName: 'DeployMenuConfig',
            bgColor: '#F6F6F8',
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/1%EF%BC%882%EF%BC%89.svg',
            },
            menuName: '菜单1',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mqygfd',
            menuCode: '',
            menuType: 2,
            backName: '菜单-rIfk1h',
            id: 42,
            configCompName: 'DeployMenuConfig',
            bgColor: '#F6F6F8',
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/1%EF%BC%883%EF%BC%89.svg',
            },
            menuName: '菜单2',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 43,
            configCompName: 'DeployMenuConfig',
          },
          {
            childPageConfig: {
              enableInfo: 0,
              enableRightFunc: 1,
              funcArea: {
                groupArr: [
                  {
                    enableGroupName: 1,
                    menuArr: [
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FAB71C',
                          icon: 'iconfont_gongdan',
                          imageUrl: '',
                        },
                        menuName: '菜单-7BcQy6',
                        type: 1,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'configMenu',
                        clientType: 2,
                        compId: 'CPiUHK',
                        menuCode: '',
                        menuType: 2,
                        id: 495,
                        configCompName: 'DeployMenuConfig',
                      },
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FC8256',
                          icon: 'iconfont_tongji',
                          imageUrl: '',
                        },
                        menuName: '菜单-W6DTXH',
                        type: 2,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'sysKnowledge',
                        clientType: 2,
                        compId: '4nwNNZ',
                        menuCode: '',
                        menuType: 2,
                        id: 496,
                        configCompName: 'DeployMenuConfig',
                      },
                    ],
                    compName: 'FuncGroup',
                    compId: 'dUTwc9',
                    rowNum: 4,
                    name: '分组(dUTwc9)',
                    configCompName: 'FuncGroupConfig',
                  },
                ],
                compId: 'ozpJc1',
                configCompName: 'FuncAreaConfig',
              },
              menuName: '菜单3',
              type: 3,
              rotateImg: {
                imgArr: [],
                compId: 'nEGyfK',
                configCompName: 'RotateImgConfig',
              },
              rightFunc: [
                {
                  icon: {
                    color: '#5A80ED',
                    icon: 'icon_gongdan',
                    imageUrl: '',
                  },
                  menuName: '23t',
                  routeName: 'sysNotification',
                  compId: 'WK62wD',
                  enableMenu: 1,
                  backName: '23',
                  id: 490,
                  configCompName: 'FixMenuConfig',
                },
              ],
              enableRotation: 1,
              id: 489,
            },
            groupCompId: 'r602xd',
            menuLevel: 1,
            icon: {
              color: '#5A80ED',
              icon: 'iconfont-guzhang',
              imageUrl:
                'http://v9.mingcloud.top:9000/v10/icon/1%EF%BC%881%EF%BC%89.svg',
            },
            menuName: '菜单3',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
            ],
            type: 3,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mr8EaL',
            menuCode: '',
            menuType: 2,
            backName: '菜单-JyevuD',
            id: 44,
            configCompName: 'DeployMenuConfig',
            bgColor: '#ECF7FD',
          },
        ],
        permission: '1',
        compName: 'FuncGroup',
        routeName: 'sysKnowledge',
        compId: 'r602xd',
        rowNum: 4,
        name: '4个 图标',
        backName: '分组(r602xd)',
        configCompName: 'FuncGroupConfig',
        showStyle: 1,
      },
      // 2-图片 4个
      {
        enableGroupName: 1,
        menuArr: [
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            menuName: '菜单1',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 480,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mqygfd',
            menuCode: '',
            menuType: 2,
            backName: '菜单-rIfk1h',
            id: 45,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gtd.alicdn.com/sns_logo/i1/TB124_3NXXXXXasXVXXSutbFXXX.jpg_240x240xz.jpg',
          },
          {
            groupCompId: 'r602xd',
            menuLevel: 2,
            menuName: '菜单2',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 481,
                sysUserMenuResourceId: null,
              },
            ],
            type: 2,
            compName: 'AppMenu',
            parentId: '',
            routeName: 'sysScan',
            clientType: 2,
            compId: 'PFYKJ8',
            menuCode: '',
            menuType: 2,
            backName: '菜单1',
            id: 481,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fbpic.588ku.com%2Felement_origin_min_pic%2F17%2F09%2F15%2F67351408baad11ce25c9b14166a049a6.jpg&refer=http%3A%2F%2Fbpic.588ku.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1635066947&t=c63342f0da92f0f8f89f021091882460',
          },
          {
            childPageConfig: {
              enableInfo: 0,
              enableRightFunc: 1,
              funcArea: {
                groupArr: [
                  {
                    enableGroupName: 1,
                    menuArr: [
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FAB71C',
                          icon: 'iconfont_gongdan',
                          imageUrl: '',
                        },
                        menuName: '菜单-7BcQy6',
                        type: 1,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'configMenu',
                        clientType: 2,
                        compId: 'CPiUHK',
                        menuCode: '',
                        menuType: 2,
                        id: 495,
                        configCompName: 'DeployMenuConfig',
                      },
                      {
                        groupCompId: 'dUTwc9',
                        menuLevel: 2,
                        icon: {
                          color: '#FC8256',
                          icon: 'iconfont_tongji',
                          imageUrl: '',
                        },
                        menuName: '菜单-W6DTXH',
                        type: 2,
                        compName: 'AppMenu',
                        parentId: 489,
                        routeName: 'sysKnowledge',
                        clientType: 2,
                        compId: '4nwNNZ',
                        menuCode: '',
                        menuType: 2,
                        id: 496,
                        configCompName: 'DeployMenuConfig',
                      },
                    ],
                    compName: 'FuncGroup',
                    compId: 'dUTwc9',
                    rowNum: 4,
                    name: '分组(dUTwc9)',
                    configCompName: 'FuncGroupConfig',
                  },
                ],
                compId: 'ozpJc1',
                configCompName: 'FuncAreaConfig',
              },
              menuName: '菜单3',
              type: 3,
              rotateImg: {
                imgArr: [],
                compId: 'nEGyfK',
                configCompName: 'RotateImgConfig',
              },
              rightFunc: [
                {
                  icon: {
                    color: '#5A80ED',
                    icon: 'icon_gongdan',
                    imageUrl: '',
                  },
                  menuName: '23t',
                  routeName: 'sysNotification',
                  compId: 'WK62wD',
                  enableMenu: 1,
                  backName: '23',
                  id: 490,
                  configCompName: 'FixMenuConfig',
                },
              ],
              enableRotation: 1,
              id: 489,
            },
            groupCompId: 'r602xd',
            menuLevel: 1,
            menuName: '菜单3',
            permission: [
              {
                check: '2',
                permissionItemId: 1,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 489,
                sysUserMenuResourceId: null,
              },
            ],
            type: 3,
            compName: 'AppMenu',
            parentId: '',
            routeName: '',
            clientType: 2,
            compId: 'mr8EaL',
            menuCode: '',
            menuType: 2,
            backName: '菜单-JyevuD',
            id: 46,
            configCompName: 'DeployMenuConfig',
            bgImgUrl:
              'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201402%2F22%2F20140222171505_rsCXj.thumb.700_0.gif&refer=http%3A%2F%2Fb-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1634991264&t=00ea34550c052ddf868e2ab427ab6ab3',
          },
        ],
        permission: '1',
        compName: 'FuncGroup',
        routeName: 'sysKnowledge',
        compId: 'r602xd',
        rowNum: 4,
        name: '4个 图片',
        backName: '分组(r602xd)',
        configCompName: 'FuncGroupConfig',
        showStyle: 2,
      },
    ],
    compId: 'n0NAK0',
    configCompName: 'FuncAreaConfig',
  },
  footerArea: {
    groupArr: [
      {
        enableGroupName: 1,
        menuArr: [
          {
            groupCompId: '',
            icon: {
              color: '#5A80ED',
              icon: 'iconfont_shuju',
              imageUrl: '',
            },
            menuName: '首页',
            permission: '',
            type: 2,
            compName: 'AppMenu',
            isFooter: true,
            routeName: '',
            compId: 'hHvdYa',
            isFixed: true,
            configCompName: 'DeployMenuConfig',
          },
          {
            groupCompId: 'trONw8',
            menuLevel: 2,
            icon: {
              color: '#5A80ED',
              icon: '',
              imageUrl: 'http://v9.mingcloud.top:9000/v10/icon/DOC.svg',
            },
            menuName: '菜单-Ul7tb1',
            permission: [
              {
                check: '1',
                permissionItemId: 1,
                menuId: 474,
                sysUserMenuResourceId: 2377,
              },
              {
                check: '2',
                permissionItemId: 2,
                menuId: 474,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 3,
                menuId: 474,
                sysUserMenuResourceId: null,
              },
              {
                check: '2',
                permissionItemId: 4,
                menuId: 474,
                sysUserMenuResourceId: null,
              },
            ],
            type: 1,
            compName: 'AppMenu',
            parentId: '',
            isFooter: true,
            routeName: '',
            clientType: 2,
            compId: 'hX6M6U',
            menuCode: '',
            menuType: 2,
            id: 474,
            configCompName: 'DeployMenuConfig',
          },
          {
            groupCompId: '',
            icon: { color: '', icon: 'iconfont-guzhang', imageUrl: '' },
            menuName: '我的',
            permission: '',
            type: 2,
            compName: 'AppMenu',
            isFooter: true,
            routeName: '',
            compId: 'ED3QMZ',
            isFixed: true,
            configCompName: 'DeployMenuConfig',
          },
        ],
        permission: '1',
        compName: 'FuncGroup',
        isFooter: true,
        routeName: 'sysKnowledge',
        compId: 'trONw8',
        rowNum: 4,
        name: '',
        configCompName: 'FuncGroupConfig',
      },
    ],
    isFooter: true,
    compId: 'kbynKO',
    configCompName: 'FuncAreaConfig',
  },
  rotateImg: {
    imgArr: [
      {
        imgUrl: 'https://cdn.uviewui.com/uview/swiper/1.jpg',
      },
      {
        imgUrl: 'https://cdn.uviewui.com/uview/swiper/2.jpg',
      },
      {
        imgUrl: 'https://cdn.uviewui.com/uview/swiper/3.jpg',
      },
    ],
    compId: 'cKDZ5s',
    configCompName: 'RotateImgConfig',
  },
  rightFunc: [
    {
      icon: { color: '#10B98A', icon: 'icon_danju', imageUrl: '' },
      menuName: '33',
      permission: [
        {
          check: '2',
          permissionItemId: 1,
          menuId: 486,
          sysUserMenuResourceId: null,
        },
        {
          check: '1',
          permissionItemId: 2,
          menuId: 486,
          sysUserMenuResourceId: 2374,
        },
        {
          check: '2',
          permissionItemId: 3,
          menuId: 486,
          sysUserMenuResourceId: null,
        },
        {
          check: '2',
          permissionItemId: 4,
          menuId: 486,
          sysUserMenuResourceId: null,
        },
      ],
      routeName: 'sysKnowledge',
      compId: '2ElfBd',
      enableMenu: 1,
      backName: '',
      id: 486,
      configCompName: 'FixMenuConfig',
    },
    {
      icon: { color: '', icon: '', imageUrl: '' },
      menuName: '',
      permission: '',
      routeName: '',
      compId: 'R2xHiz',
      enableMenu: 0,
      configCompName: 'FixMenuConfig',
    },
  ],
  enableRotation: 1,
  enableNotice: 1,
  notice: {
    compId: 'GUjwSq',
    rotateSpeed: 5,
    style: 1,
    rotateType: 1,
    configCompName: 'NoticeConfig',
  },
  info: {
    compId: '6sxYwW',
    name: '行业资讯',
    term: 1,
    time: 1,
    configCompName: 'AppInfoConfig',
  },
};